### ISSUE TITLE
Make a Health Check

### ISSUE THREAD

**Issue by jgurr4** [jeremygurr/visur#1]
Make a verticle that gets started by the Main verticle which is called 'HealthCheckVerticle'. It's purpose is to provide a endpoint to users who want to check the health of our application to see if it's running. So it needs to be able to open a HTTP endpoint at some specific port number, then any request made to that port number needs to respond with 'app is healthy' or something like that to let the user know the app is running properly. If no response happens then we can assume the app is down.

**Comment by jgolden5** [comment]
Requires #3
