### ISSUE TITLE
create model boundaries so cursor does not go off-screen

### ISSUE THREAD

**Issue by jgolden5** [jeremygurr/visur#24]
- [x] add width & height to model
- [x] rename browserInputVerticle to KeyWasPressedVerticle, and add a canvasWasChangedVerticle
- [x] send initial width/height from browser to the model (through BrowserInputVerticle)
- [x] prevent cursor from going out of bounds when x and y are less than 0
- [x] prevent cursor from going out of bounds when x or y are greater than canvasWidth and canvasHeight
Should not need to touch browser output or anything afterwards in the command flow

**Comment by git-jgolden1** [comment]
- [ ] add width & height to model
- [ ] send initial width/height from browser to the model (through BrowserInputVerticle)
- [ ] use that width/height to prevent cursor from going off screen in the browser
Should not need to touch browser output or anything afterwards in the command flow
