### ISSUE TITLE
Show real content on screen and be able to handle multi-line support

### ISSUE THREAD

**Issue by jgolden5** [jeremygurr/visur#25]
- [x] create line wrapping for content 
- [x] create multi-line test content to test for line wrapping capability

**Comment by git-jgolden1** [comment]
- [ ] create single-line test content in the model using the BrowserInputVerticle
- [ ] create multi-line test content to test for line wrapping capability
- [ ] update view based on modelChanged event (in the BrowserOutputVerticle)
- [ ] update canvas based on viewWasChanged event (in the browser)

**Comment by git-jgolden1** [comment]
after this one: #26 #33 #27
