### ISSUE TITLE
Finish reading Vert.x Core until the section "Using the file system with Vert.x," inclusive

### ISSUE THREAD

**Issue by jgolden5** [jeremygurr/visur#8]

**Comment by git-jgolden1** [comment]
[vertxCoreNotes.txt](https://github.com/jeremygurr/visur/files/12620870/vertxCoreNotes.txt)

bookmark = https://vertx.io/docs/vertx-core/java/#_http1_x_pooling_and_keep_alive

**Comment by jgolden5** [comment]
1. status 100 (continue): this means that the server IS going to be able to accept the request sent by the the client, and this status is received by the client

2. vertx allows you to set a continueHandler on the client request object, which is called if a status 100 is sent by the server

3. http tunnel: used to create a secure network link between 2 computers in conditions of restricted network connectivity. This tunnel is created by an intermediary known as a proxy server (we do this in visur)

4. http tunnel can be called on a request instance using connect() method

5. server push is an http/2 feature that enables sending multiple responses in parallel for a single client request

6. a push handler can be set on a request to receive the request/response pushed by the server

7. if the client does not want to receive a pushed request, it can reset the stream with pushedRequest.reset()

8. when no push handler is set, any stream pushed will be automatically cancelled by the client with a stream reset (resulting in error code of 8)

9. to receive custom frames, response.customFrameHandler() can be used

10. check for whether a server compressed the body with the content-encoding header in the response sent back to it

bookmark = https://vertx.io/docs/vertx-core/java/#_http1_x_pooling_and_keep_alive

**Comment by jgolden5** [comment]
Finally!
